baseurl: ''
title: 'QLSC 612: Neuro Data Science'
theme: hugo-universal-theme
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: about
          name: About
          url: /about/
          weight: 2
        - identifier: schedule
          name: Schedule
          url: /schedule/
          weight: 3
        - identifier: setup
          name: Setup
          url: /setup/
          weight: 4
        - identifier: coc
          name: Code of Conduct
          url: /coc/
          weight: 5
      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/neurodatascience/NeuroDataSci-course-2020/'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 2
          name: Email
          url: 'mailto:jean-baptiste.poline@.mcgill.ca'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      viewMorePostLink: /blog/
      author: BHS
      defaultKeywords:
        - BrainHack
        - Neuroscience
      mainSections:
        - blog
      defaultDescription: Neuro Data Science
      facebook_site: ''
      twitter_site: ''
      default_sharing_image: img/brainhackSchool.jpg
      googleMapsApiKey:
      style: green
      email:
      contact_form_ajax: false
      about_us: >-
        <p>Fundamentals and project in neural data science.</p>
      copyright: 'Copyright (c) 2020, Neuro Data Science; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: false
      instructors:
        enable: false
      features:
        enable: true
      testimonials:
        enable: false
        title: ''
        subtitle: ''
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Fundamental for Neuro Data Science'
        subtitle: A week-long introduction to the foundations of neuro- and data science, in preparation for the [BrainHack School](https://school.brainhackmtl.org/).
        link_url: about/
        link_text: Learn more
      clients:
        enable: false
        title: Partner institutions
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: true
        text: >-
          <b>NOTE</b>: Due to the [COVID-19](https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/) pandemic this year will be entirely virtual!

Permalinks:
  blog: '/blog/:year/:month/:day/:filename/'

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

disqusShortname: ''
googleAnalytics: ''
paginate: 10
